AWSTemplateFormatVersion: '2010-09-09'
Description: "Desafio DIO 4 - Infraestrutura Automatizada no AWS CloudFormation com EC2 + S3 + Security Group"

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Permitir acesso SSH e HTTP"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0bdd88bd06d16ba03
      InstanceType: t3.micro
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      KeyName: Name
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Desafio 4: Stake no CloudFormation Servidor Web e Bucket S3!!!</h1>" > /var/www/html/index.html
      Tags:
        - Key: Name
          Value: ServidorWeb

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "isa-desafio4-cloudformation-${AWS::AccountId}"
      AccessControl: Private
